# Generated by Django 3.2.9 on 2021-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211127_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='shipping_cost',
        ),
    ]
